curl -s 'https://p2p.binance.com/bapi/c2c/v2/friendly/c2c/adv/search' \
  -H 'accept-language: ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,sr;q=0.6' \
  -H 'cache-control: no-cache' \
  -H 'clienttype: web' \
  -H 'content-type: application/json' \
  -H 'lang: ru' \
  -H 'pragma: no-cache' \
  -H 'referer: https://p2p.binance.com/ru/trade/KaspiBank/USDT?fiat=KZT' \
  -H 'sec-ch-ua: "Google Chrome";v="111", "Not(A:Brand";v="8", "Chromium";v="111"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36' \
  -H 'x-passthrough-token;' \
  -H 'x-trace-id: 0699bc95-5768-429c-8060-af9ff98fb9d4' \
  -H 'x-ui-request-trace: 0699bc95-5768-429c-8060-af9ff98fb9d4' \
  --data-raw '{"rows": <rows>, "page": <page>, "fiat":"KZT","transAmount":"50000","tradeType":"buy","asset":"USDT","countries":[],"proMerchantAds":false,"publisherType":null,"payTypes":["KaspiBank"]}' \
  --compressed \
